# Imports


In [3]:
import numpy as np
import pandas as pd
import matplotlib
import sys
print("Numpy", np.__version__)
print("Pandas", pd.__version__)
print("Matplotlib", matplotlib.__version__)
print("Python", sys.version)

Numpy 1.26.4
Pandas 2.2.2
Matplotlib 3.9.2
Python 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]


# Basic Neuron 🧠

In [4]:
inputs = [1.2, 5.1, 2.1] # 3 inputs are the three neurons from previous layer
weights= [3.1, 2.1, 8.7] # 3 weights are the weights of the three neurons from previous layer
bias = 3 # bias is the bias of the neuron from the previous layer

output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias  # output is the output of the neuron from the previous layer
print(output)

35.7


# Initiate a Layer 🥞

Four Inputs into Four Neurons

In [5]:
inputs = [1, 2, 3, 2.5] # 3 inputs are the four neurons from previous layer
weights= [0.2, 0.8, -0.5, 1.0] # 3 weights are the weights of the four neurons from previous layer
bias = 2 # bias is the bias of the neuron from the previous layer

output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + inputs[3]*weights[3]+ bias  # output is the output of the neuron from the previous layer
print(output)

4.8


Four Inputs into Three Neurons

In [6]:
inputs = [1, 2, 3, 2.5] # 4 inputs are the four neurons from previous layer

weights1= [0.2, 0.8, -0.5, 1.0] # 3 weights are the weights of the four neurons from previous layer
weights2= [0.5, -0.91, 0.26, -0.5]
weights3= [-0.26, -0.27, 0.17, 0.87]
bias1 = 2 # bias is the bias of the neuron from the previous layer
bias2 = 3
bias3 = 0.5

output = [inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3]+ bias1, 
          inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3]+ bias2,
          inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[3]*weights3[3]+ bias3]  # output is the layered output of the neurons from the previous layer
print(output)

[4.8, 1.21, 2.385]


Simplifying the previous code

In [7]:
inputs = [1, 2, 3, 2.5] # 4 inputs are the four neurons from previous layer
weights= [[0.2, 0.8, -0.5, 1.0],
          [0.5, -0.91, 0.26, -0.5],
          [-0.26, -0.27, 0.17, 0.87]] # 3 weights are the weights of the four neurons from previous layer
biases = [2, 3, 0.5] # bias is the bias of the neuron from the previous layer

layer_outputs = [] # Output of current layer
for neuron_weights, neuron_bias in zip(weights, biases): #Zip is used to iterate over two lists at the same time and make a list of lists
    neuron_output = 0 # Output of given neuron
    for n_input, weight in zip(inputs, neuron_weights): #Zip is used to iterate over two lists at the same time
        neuron_output += n_input*weight # Multiply the input with the weight and add it to the neuron_output
    neuron_output += neuron_bias # Add the bias to the neuron_output
    layer_outputs.append(neuron_output) # Append the neuron_output to the layer_outputs

print(layer_outputs)

[4.8, 1.21, 2.385]


# Dot Product and Matrix Product 🔃

In [ ]:
inputs = [1, 2, 3, 2.5]
weights= [0.2, 0.8, -0.5, 1.0] # 3 weights are the weights of the four neurons from previous layer
bias = 2 # bias is the bias of the neuron from the previous layer

output = np.dot(weights, inputs) + bias # np.dot is used to multiply the weights and inputs and add them together
print(output)

4.8


In [ ]:
inputs = [1, 2, 3, 2.5] # 4 inputs are the four neurons from previous layer
weights= [[0.2, 0.8, -0.5, 1.0],
          [0.5, -0.91, 0.26, -0.5],
          [-0.26, -0.27, 0.17, 0.87]] # 3 weights are the weights of the four neurons from previous layer
biases = [2, 3, 0.5]

output = np.dot(weights, inputs) + biases # np.dot is used to multiply the weights and inputs and add them together
print(output)

[4.8   1.21  2.385]


# Batch Sizing 📦🔢

In [ ]:
inputs = [[1, 2, 3, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]] # inputs are the four neurons from previous layer(3,4)

weights= [[0.2, 0.8, -0.5, 1.0],
          [0.5, -0.91, 0.26, -0.5],
          [-0.26, -0.27, 0.17, 0.87]] # weights are the weights of the four neurons from previous layer(3,4)

biases = [2, 3, 0.5]

# output = np.dot(weights, inputs) + biases # np.dot is used to multiply the weights and inputs and add them together(3,4) * (3,4) = Error
output = np.dot(inputs, np.array(weights).T) + biases # np.dot is used to multiply the weights and inputs and add them together(3,4) * (4,3) = (3,3)
# T or Transpose is used to convert the weights from (3,4) to (4,3) to make the multiplication possible
print(output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


MultiLayered Approach

In [17]:
inputs = [[1, 2, 3, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]] # inputs are the four neurons from previous layer(3,4)

weights= [[0.2, 0.8, -0.5, 1.0],
          [0.5, -0.91, 0.26, -0.5],
          [-0.26, -0.27, 0.17, 0.87]] # weights are the weights of the four neurons from previous layer(3,4)

weights2= [[0.1, -0.14, 0.5],
          [-0.5, 0.12, -0.33],
          [-0.44, 0.73, -0.13]]

biases = [2, 3, 0.5]

biases2 = [-1, 2, -0.5]

# output = np.dot(weights, inputs) + biases # np.dot is used to multiply the weights and inputs and add them together(3,4) * (3,4) = Error
layer1_outputs = np.dot(inputs, np.array(weights).T) + biases # np.dot is used to multiply the weights and inputs and add them together(3,4) * (4,3) = (3,3)
# T or Transpose is used to convert the weights from (3,4) to (4,3) to make the multiplication possible
layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2
print(layer2_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


# Objectification of the Layers 🛤️📚

In [22]:
X = [[1, 2, 3, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]] # X denotes inputs

np.random.seed(0) # Seed is used to generate the same random numbers every time


class Layer_Dense: # Class for the dense layer- Hidden layer
    def __init__(self, n_inputs, n_neurons): #Entry point for the class object
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons) # Random weights of the neurons
        self.biases = np.zeros((1, n_neurons)) # Zero biases of the neurons
    def forward(self, inputs): # Forward function to calculate the output
        self.output = np.dot(inputs, self.weights) + self.biases # Output of the neurons

layer1 = Layer_Dense(4,5) # Layer 1 with 4 inputs and 5 neurons
layer2 = Layer_Dense(5,2) # Layer 2 with 5 inputs and 2 neurons
layer1.forward(X) # Forward function of layer 1
layer2.forward(layer1.output) # Forward function of layer 2


print("Layer 2 Output:",layer2.output) # Output of layer 1
# print(0.10*np.random.randn(4, 3)) # Random weights of the neurons

Layer 2 Output: [[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]
